development:
  secret_key_base: 295db337ba61ec5f14529c395e3c86e607df732ff3e1963683cb5da98fe1d2c905e6b42d18b12c5fdd3c64355c82b2e18a636d6095dc5e492abce45d5c86bca0
  fitbit_api_client_id: your_client_id_here
  fitbit_api_client_secret: your_client_secret_here
  fitbit_api_scope: activity profile sleep heartrate nutrition location weight social settings

test:
  secret_key_base: ea61cdb81d7b17e33fe06e5a59f8d0666eb9ce585a79588357db0f24da7c5e7743050c3071b9c41c9a51f1b2a241e51bf60300081d559dbdb76e08f3561bf66e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
